spring:
  application:
    name: newsquery
  elasticsearch:
    uris: "http://localhost:9200"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

newsquery:
  elasticsearch:
    index: news
  embedding:
    service-url: "http://localhost:8000"
